import * as fs from 'fs';
import * as path from 'path';

import type { GodotSpriteMap } from './godot-resources.ts';

// ---------------------------------------------------------------------------
// Output types (consumed by the runtime in Phase 4)
// ---------------------------------------------------------------------------

export interface CutsceneData {
  nodes: Record<string, CutsceneNode>;
  animations: Record<string, CutsceneAnimation>;
}

export interface CutsceneNode {
  type: string;
  /** Resolved PixiJS frame or animation name (e.g. "rat-boat#0", "captain") — Sprite2D only */
  pixiTexture?: string;
  /** Static text content — Label only */
  text?: string;
  /** Font size in pixels from LabelSettings — Label only */
  fontSize?: number;
  /** Width of the label rect (offset_right − offset_left) — Label only */
  width?: number;
  /** Height of the label rect (offset_bottom − offset_top) — Label only */
  height?: number;
}

export interface CutsceneAnimation {
  /** Duration in seconds */
  length: number;
  tracks: CutsceneTrack[];
  /** Sound effects triggered at specific times during this animation */
  audioCues: CutsceneAudioCue[];
}

export interface CutsceneAudioCue {
  /** Asset manifest alias (e.g. "sounds/Cat Meow B.wav") */
  sound: string;
  /** Trigger time in seconds */
  time: number;
}

export interface CutsceneTrack {
  /** Name of the scene node this track animates */
  node: string;
  /** Godot property name, e.g. "position", "rotation", "modulate:a" */
  property: string;
  interpolation: 'nearest' | 'linear' | 'cubic';
  keyframes: CutsceneKeyframe[];
}

export interface CutsceneKeyframe {
  /** Time in seconds */
  time: number;
  /** Parsed value: {x,y} for Vector2, {r,g,b,a} for Color, number, boolean */
  value: unknown;
  /** Godot easing curve value (1 = linear) */
  transition: number;
}

// ---------------------------------------------------------------------------
// Internal parser types
// ---------------------------------------------------------------------------

interface TscnSection {
  /** Section type: "gd_scene", "ext_resource", "sub_resource", "node" */
  type: string;
  /** Attributes from the section header, still quoted */
  attrs: Record<string, string>;
  /** Key=value pairs from the section body */
  props: Map<string, string>;
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/**
 * Scan godotCutscenesDir for .tscn files, convert each to a cutscene JSON,
 * and write them to outputDir. Also generates a TypeScript types file at
 * typesOutputPath so the runtime gets fully-typed node maps per cutscene.
 *
 * Called from generateTypeDefinitions() after the asset build completes.
 * Reads godot/sprite-map.json to resolve texture references to PixiJS names.
 */
export function generateCutsceneJsonFiles(
  godotCutscenesDir: string,
  outputDir: string,
  spriteMapPath: string,
  typesOutputPath: string,
): void {
  const spriteMap: GodotSpriteMap = fs.existsSync(spriteMapPath)
    ? JSON.parse(fs.readFileSync(spriteMapPath, 'utf-8'))
    : {};

  if (!fs.existsSync(godotCutscenesDir)) return;

  fs.mkdirSync(outputDir, { recursive: true });

  const tscnFiles = fs.readdirSync(godotCutscenesDir).filter((f) => f.endsWith('.tscn'));
  const parsed = new Map<string, CutsceneData>();

  for (const file of tscnFiles) {
    const name = file.replace('.tscn', '');
    const content = fs.readFileSync(path.join(godotCutscenesDir, file), 'utf-8');
    const cutscene = parseTscn(content, spriteMap);
    fs.writeFileSync(path.join(outputDir, `${name}.json`), JSON.stringify(cutscene, null, 2));
    parsed.set(name, cutscene);
    console.log(`[Godot] Cutscene → ${name}.json (${Object.keys(cutscene.animations).length} animation(s))`);
  }

  writeCutsceneTypes(parsed, typesOutputPath);
}

/**
 * Generate src/assets/cutscenes.ts — typed node maps and animation name unions
 * for every .tscn file, so CutscenePlayer gets full autocompletion.
 */
function writeCutsceneTypes(cutscenes: Map<string, CutsceneData>, outputPath: string): void {
  if (cutscenes.size === 0) return;

  const lines: string[] = [
    `// AUTO-GENERATED by the asset pipeline — do not edit manually`,
    `import type { Container } from 'pixi.js';`,
    ``,
    `/**`,
    ` * Maps each cutscene filename (without extension) to its Sprite2D node names.`,
    ` *`,
    ` * Usage:`,
    ` *   new CutscenePlayer<CutsceneNodeMap['rat-cat'], CutsceneAnimationMap['rat-cat']>(data)`,
    ` */`,
    `export type CutsceneNodeMap = {`,
  ];

  for (const [name, data] of cutscenes) {
    lines.push(`  '${name}': {`);
    for (const [nodeName, node] of Object.entries(data.nodes)) {
      if (node.type === 'Sprite2D' || node.type === 'Label') lines.push(`    ${nodeName}: Container;`);
    }
    lines.push(`  };`);
  }

  lines.push(`};`, ``);
  lines.push(`/** Maps each cutscene filename to its available animation names. */`);
  lines.push(`export type CutsceneAnimationMap = {`);

  for (const [name, data] of cutscenes) {
    const anims = Object.keys(data.animations).map((a) => `'${a}'`).join(' | ') || 'never';
    lines.push(`  '${name}': ${anims};`);
  }

  lines.push(`};`, ``);

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join('\n'));
  console.log(`[Godot] Cutscene types → ${outputPath}`);
}

/**
 * Parse a Godot 4 .tscn file into a CutsceneData object.
 * Exported for testing.
 */
export function parseTscn(content: string, spriteMap: GodotSpriteMap): CutsceneData {
  const sections = parseSections(content);

  // Build reverse lookup: res:// path → PixiJS name
  const godotPathToPixi: Record<string, string> = {};
  for (const entry of Object.values(spriteMap)) {
    const name = entry.pixiAnimation ?? entry.pixiFrame ?? '';
    if (name) godotPathToPixi[entry.godotPath] = name;
  }

  // ExtResources: id → res:// path
  const extResources: Record<string, string> = {};
  for (const s of sections) {
    if (s.type !== 'ext_resource') continue;
    const id = unquote(s.attrs.id ?? '');
    const resPath = unquote(s.attrs.path ?? '');
    if (id && resPath) extResources[id] = resPath;
  }

  // AudioStreamPlayer nodes: node name → sound alias (filename without extension)
  const audioNodeToSound: Record<string, string> = {};
  for (const s of sections) {
    if (s.type !== 'node') continue;
    if (unquote(s.attrs.type ?? '') !== 'AudioStreamPlayer') continue;
    const name = unquote(s.attrs.name ?? '');
    const extId = s.props.get('stream')?.match(/ExtResource\("([^"]+)"\)/)?.[1];
    if (name && extId && extResources[extId]) {
      // "res://sounds/Cat Meow B.wav" → "sounds/Cat Meow B.wav" (matches the asset manifest alias)
      audioNodeToSound[name] = extResources[extId].replace(/^res:\/\//, '');
    }
  }

  // LabelSettings sub-resources: id → { fontSize }
  const labelSettingsById: Record<string, { fontSize?: number }> = {};
  for (const s of sections) {
    if (s.type !== 'sub_resource') continue;
    if (unquote(s.attrs.type ?? '') !== 'LabelSettings') continue;
    const id = unquote(s.attrs.id ?? '');
    if (!id) continue;
    const fontSizeStr = s.props.get('font_size');
    labelSettingsById[id] = {
      fontSize: fontSizeStr !== undefined ? parseInt(fontSizeStr, 10) : undefined,
    };
  }

  // Animation sub-resources: id → data
  const animById: Record<string, {
    name?: string;
    length: number;
    tracks: CutsceneTrack[];
    audioCues: CutsceneAudioCue[];
  }> = {};
  for (const s of sections) {
    if (s.type !== 'sub_resource') continue;
    if (unquote(s.attrs.type ?? '') !== 'Animation') continue;
    const id = unquote(s.attrs.id ?? '');
    if (!id) continue;
    animById[id] = {
      name: s.props.has('resource_name') ? unquote(s.props.get('resource_name')!) : undefined,
      length: parseFloat(s.props.get('length') ?? '0'),
      tracks: parseAnimTracks(s.props),
      audioCues: parseAudioCues(s.props, audioNodeToSound),
    };
  }

  // AnimationLibrary: animation name → sub-resource id
  const animNameToId: Record<string, string> = {};
  for (const s of sections) {
    if (s.type !== 'sub_resource') continue;
    if (unquote(s.attrs.type ?? '') !== 'AnimationLibrary') continue;
    parseAnimLibraryData(s.props.get('_data') ?? '', animNameToId);
  }

  // Scene nodes: name → {type, pixiTexture}
  const nodes: Record<string, CutsceneNode> = {};
  for (const s of sections) {
    if (s.type !== 'node') continue;
    const name = unquote(s.attrs.name ?? '');
    const type = unquote(s.attrs.type ?? '');
    if (!name || !type) continue;

    const node: CutsceneNode = { type };

    if (type === 'Sprite2D') {
      const texProp = s.props.get('texture');
      if (texProp) {
        const extId = texProp.match(/ExtResource\("([^"]+)"\)/)?.[1];
        if (extId && extResources[extId]) {
          node.pixiTexture = godotPathToPixi[extResources[extId]];
        }
      }
    }

    if (type === 'Label') {
      const textProp = s.props.get('text');
      if (textProp !== undefined) node.text = unquote(textProp);

      const offsetLeft = parseFloat(s.props.get('offset_left') ?? '0');
      const offsetTop = parseFloat(s.props.get('offset_top') ?? '0');
      const offsetRight = parseFloat(s.props.get('offset_right') ?? '0');
      const offsetBottom = parseFloat(s.props.get('offset_bottom') ?? '0');
      if (offsetRight > offsetLeft) node.width = offsetRight - offsetLeft;
      if (offsetBottom > offsetTop) node.height = offsetBottom - offsetTop;

      const labelSettingsProp = s.props.get('label_settings');
      if (labelSettingsProp) {
        const subId = labelSettingsProp.match(/SubResource\("([^"]+)"\)/)?.[1];
        if (subId && labelSettingsById[subId]?.fontSize !== undefined) {
          node.fontSize = labelSettingsById[subId].fontSize;
        }
      }
    }

    nodes[name] = node;
  }

  // Build output animations, skipping Godot's internal RESET animation
  const animations: Record<string, CutsceneAnimation> = {};
  for (const [animName, animId] of Object.entries(animNameToId)) {
    if (animName === 'RESET') continue;
    const anim = animById[animId];
    if (!anim) continue;
    animations[animName] = { length: anim.length, tracks: anim.tracks, audioCues: anim.audioCues };
  }

  return { nodes, animations };
}

// ---------------------------------------------------------------------------
// Section parser
// ---------------------------------------------------------------------------

function parseSections(content: string): TscnSection[] {
  const headerRe = /^\[([^\]]+)\]/gm;
  const matches = [...content.matchAll(headerRe)];
  const sections: TscnSection[] = [];

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    const headerContent = m[1];
    const bodyStart = m.index! + m[0].length;
    const bodyEnd = i + 1 < matches.length ? matches[i + 1].index! : content.length;
    const body = content.slice(bodyStart, bodyEnd);

    // First token of the header is the section type
    const spaceIdx = headerContent.search(/\s/);
    const type = spaceIdx >= 0 ? headerContent.slice(0, spaceIdx) : headerContent;
    const attrStr = spaceIdx >= 0 ? headerContent.slice(spaceIdx) : '';

    // Parse key="value" or key=bareValue attributes from header
    const attrs: Record<string, string> = {};
    const attrRe = /(\w+)=("(?:[^"\\]|\\.)*"|[\w./:{}@-]+)/g;
    let am: RegExpExecArray | null;
    while ((am = attrRe.exec(attrStr)) !== null) {
      attrs[am[1]] = am[2];
    }

    sections.push({ type, attrs, props: parseProps(body) });
  }

  return sections;
}

/**
 * Parse a section body into key → value pairs.
 * Handles multi-line brace-enclosed blocks (e.g. tracks/N/keys = { ... }).
 */
function parseProps(body: string): Map<string, string> {
  const result = new Map<string, string>();
  const lines = body.split('\n');
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const eqIdx = line.indexOf(' = ');
    if (eqIdx < 0) { i++; continue; }

    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 3).trimEnd();

    // Multi-line block: accumulate until brace depth returns to 0
    if (value.trimStart().startsWith('{')) {
      let depth = countChar(value, '{') - countChar(value, '}');
      i++;
      while (i < lines.length && depth > 0) {
        value += '\n' + lines[i];
        depth += countChar(lines[i], '{') - countChar(lines[i], '}');
        i++;
      }
    } else {
      i++;
    }

    if (key) result.set(key, value.trim());
  }

  return result;
}

function countChar(str: string, ch: string): number {
  let n = 0;
  for (let i = 0; i < str.length; i++) if (str[i] === ch) n++;
  return n;
}

// ---------------------------------------------------------------------------
// Animation track parsing
// ---------------------------------------------------------------------------

function parseAnimTracks(props: Map<string, string>): CutsceneTrack[] {
  // Collect track indices
  const indices = new Set<number>();
  for (const key of props.keys()) {
    const m = key.match(/^tracks\/(\d+)\//);
    if (m) indices.add(Number(m[1]));
  }

  const tracks: CutsceneTrack[] = [];

  for (const idx of [...indices].sort((a, b) => a - b)) {
    // Only handle "value" tracks; skip "bezier", "audio", etc.
    if (unquote(props.get(`tracks/${idx}/type`) ?? '') !== 'value') continue;
    if (props.get(`tracks/${idx}/enabled`) === 'false') continue;

    const pathProp = props.get(`tracks/${idx}/path`) ?? '';
    const nodePath = pathProp.match(/NodePath\("([^"]+)"\)/)?.[1];
    if (!nodePath) continue;

    // "AnimationPlayer/CatTail:position" → node="CatTail", property="position"
    const colonIdx = nodePath.lastIndexOf(':');
    const property = nodePath.slice(colonIdx + 1);
    const nodeName = nodePath.slice(0, colonIdx).split('/').pop()!;

    const interp = parseInt(props.get(`tracks/${idx}/interp`) ?? '1');
    const keysStr = props.get(`tracks/${idx}/keys`) ?? '';
    const keyframes = parseKeyframes(keysStr);
    if (keyframes.length === 0) continue;

    tracks.push({
      node: nodeName,
      property,
      interpolation: interpMode(interp),
      keyframes,
    });
  }

  return tracks;
}

/**
 * Parse "audio" type tracks into audio cues using the supplied node→sound map.
 * Audio tracks have a "times" array and reference an AudioStreamPlayer node
 * whose stream was resolved to a sound alias at scene-parse time.
 */
function parseAudioCues(
  props: Map<string, string>,
  audioNodeToSound: Record<string, string>,
): CutsceneAudioCue[] {
  const indices = new Set<number>();
  for (const key of props.keys()) {
    const m = key.match(/^tracks\/(\d+)\//);
    if (m) indices.add(Number(m[1]));
  }

  const cues: CutsceneAudioCue[] = [];

  for (const idx of [...indices].sort((a, b) => a - b)) {
    if (unquote(props.get(`tracks/${idx}/type`) ?? '') !== 'audio') continue;
    if (props.get(`tracks/${idx}/enabled`) === 'false') continue;

    const pathProp = props.get(`tracks/${idx}/path`) ?? '';
    const nodePath = pathProp.match(/NodePath\("([^"]+)"\)/)?.[1];
    if (!nodePath) continue;

    // Audio track path has no ":property" suffix — just "AnimationPlayer/CatMeowB"
    const nodeName = nodePath.split('/').pop()!;
    const soundAlias = audioNodeToSound[nodeName];
    if (!soundAlias) continue;

    const keysStr = props.get(`tracks/${idx}/keys`) ?? '';
    const timesM = keysStr.match(/"times":\s*PackedFloat32Array\(([^)]*)\)/);
    if (!timesM) continue;

    const times = timesM[1]
      .split(',')
      .map((s) => parseFloat(s.trim()))
      .filter((n) => !isNaN(n));

    for (const time of times) {
      cues.push({ sound: soundAlias, time });
    }
  }

  return cues;
}

function interpMode(n: number): 'nearest' | 'linear' | 'cubic' {
  if (n === 0) return 'nearest';
  if (n === 2 || n === 4) return 'cubic';
  return 'linear';
}

// ---------------------------------------------------------------------------
// Keyframe parsing
// ---------------------------------------------------------------------------

function parseKeyframes(keysStr: string): CutsceneKeyframe[] {
  // keysStr is the multi-line { ... } block from the keys property
  const timesM = keysStr.match(/"times":\s*PackedFloat32Array\(([^)]*)\)/);
  const transM = keysStr.match(/"transitions":\s*PackedFloat32Array\(([^)]*)\)/);
  // [^\]]* safely matches across newlines (character class includes \n by default)
  const valsM = keysStr.match(/"values":\s*\[([^\]]*)\]/);

  if (!timesM || !valsM) return [];

  const times = timesM[1]
    .split(',')
    .map((s) => parseFloat(s.trim()))
    .filter((n) => !isNaN(n));

  const transitions = transM
    ? transM[1].split(',').map((s) => parseFloat(s.trim())).filter((n) => !isNaN(n))
    : times.map(() => 1);

  const values = parseValues(valsM[1]);

  return times.map((time, i) => ({
    time,
    value: values[i] ?? null,
    transition: transitions[i] ?? 1,
  }));
}

/**
 * Parse a comma-separated list of Godot value literals.
 * Handles: Vector2, Color, boolean, number.
 */
function parseValues(str: string): unknown[] {
  const result: unknown[] = [];
  let remaining = str.trim();

  while (remaining.length > 0) {
    let advanced = false;

    // Vector2(x, y)
    const v2 = remaining.match(/^Vector2\(([^)]+)\)/);
    if (v2) {
      const [x, y] = v2[1].split(',').map((s) => parseFloat(s.trim()));
      result.push({ x, y });
      remaining = remaining.slice(v2[0].length).replace(/^\s*,?\s*/, '');
      advanced = true;
    }

    // Color(r, g, b, a)
    if (!advanced) {
      const col = remaining.match(/^Color\(([^)]+)\)/);
      if (col) {
        const parts = col[1].split(',').map((s) => parseFloat(s.trim()));
        result.push({ r: parts[0], g: parts[1], b: parts[2], a: parts[3] ?? 1 });
        remaining = remaining.slice(col[0].length).replace(/^\s*,?\s*/, '');
        advanced = true;
      }
    }

    // true / false
    if (!advanced) {
      const bool = remaining.match(/^(true|false)/);
      if (bool) {
        result.push(bool[1] === 'true');
        remaining = remaining.slice(bool[0].length).replace(/^\s*,?\s*/, '');
        advanced = true;
      }
    }

    // number (int or float, optional sign/exponent)
    if (!advanced) {
      const num = remaining.match(/^-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/);
      if (num) {
        result.push(parseFloat(num[0]));
        remaining = remaining.slice(num[0].length).replace(/^\s*,?\s*/, '');
        advanced = true;
      }
    }

    if (!advanced) break; // Unknown token; stop rather than loop forever
  }

  return result;
}

// ---------------------------------------------------------------------------
// AnimationLibrary parsing
// ---------------------------------------------------------------------------

function parseAnimLibraryData(dataStr: string, out: Record<string, string>): void {
  // &"animName": SubResource("Animation_id")
  const re = /&"([^"]+)":\s*SubResource\("([^"]+)"\)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(dataStr)) !== null) {
    out[m[1]] = m[2];
  }
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function unquote(s: string): string {
  return s.replace(/^"|"$/g, '');
}
